name: C/C++ CI

on:
  push:
    branches: [ tests ]
  pull_request:
    branches: [ tests ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build lib
      env:
        COMPILER: g++
      run: |
        cd ./stdex
        chmod a+rwx ./build_lib.sh
        ./build_lib.sh
        cd ..
    - name: build tests
      env:
        COMPILER: g++
      run: |
        chmod a+rwx ./build_tests.sh
        ./build_tests.sh
    - name: run tests
      run: |
        chmod a+rwx ./run_tests.sh
        ./run_tests.sh
